app:
  jwt:
    cookie-secure: true
  security:
    require-https: true

server:
  ssl:
    enabled: true
    key-store: ${TLS_KEY_STORE}
    key-store-password: ${TLS_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${TLS_KEY_ALIAS:task-management}
